import {createRoute,Link} from '@tanstack/react-router';
import {useEffect,useState} from 'react';
import {Route as root} from './__root';
import {pageHead} from '../lib/head';
import {useCoffee} from '../components/state';
import {RecipeCard,Screen} from '../components/common';
import {shareRecipe} from '../lib/coffee';
export const Route=createRoute({getParentRoute:()=>root,path:'/decisions',head:()=>pageHead('My Decisions — Pour Decisions','Only the good ones made the cut. Your saved coffee recipes and finished drinks.'),component:Decisions});
function Decisions(){const{saved,deleteDecision,removePhoto,toast,updateDraft}=useCoffee();const[expanded,setExpanded]=useState<string|null>(null);useEffect(()=>{window.scrollTo(0,0);},[]);return <Screen title="MY DECISIONS" sub="Only the good ones made the cut."><div className="space-y-4">{!saved.length&&<div className="card-cozy p-8 text-center"><p>No decisions yet. Go make a good one ☕</p><Link to="/" className="btn-primary mt-6" onClick={()=>updateDraft({step:'home'})}>+ New</Link></div>}{saved.map(d=><article className="card-cozy overflow-hidden" key={d.id}><button className="flex items-center gap-4 p-4 w-full text-left" aria-expanded={expanded===d.id} onClick={()=>setExpanded(expanded===d.id?null:d.id)}>{d.photo?<img src={d.photo} className="size-20 object-cover rounded-2xl shrink-0" alt={d.recipe.name}/>:<div className="size-20 bg-crema rounded-2xl flex items-center justify-center text-3xl shrink-0">☕</div>}<div className="min-w-0"><h2 className="font-display text-xl font-bold">{d.recipe.name}</h2><p className="text-sm text-muted-foreground">{d.recipe.temp==='hot'?'🔥 Hot':'🧊 Iced'} · {new Date(d.date).toLocaleDateString()}</p></div><span className="ml-auto" aria-hidden="true">{expanded===d.id?'−':'+'}</span></button>{expanded===d.id&&<div className="p-4 space-y-4"><RecipeCard recipe={d.recipe}/>{d.photo&&<button type="button" className="underline min-h-11 w-full text-sm" onClick={()=>removePhoto(d.id)}>Remove photo</button>}<dl className="grid grid-cols-2 gap-2 text-sm">{Object.entries(d.taste).map(([key,value])=><div key={key}><dt className="capitalize font-semibold">{key}</dt><dd>{value}/100</dd></div>)}<div><dt className="font-semibold">Temperature choice</dt><dd className="capitalize">{d.temp==='surprise'?'Surprise Me':d.temp}</dd></div></dl><div className="flex gap-2"><button className="btn-secondary flex-1" onClick={()=>void shareRecipe(d.recipe,toast)}>Share</button><button className="btn-secondary flex-1" onClick={()=>deleteDecision(d.id)}>Delete</button></div></div>}</article>)}</div></Screen>;}
