import {test} from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';import {makeRecipe,addItems,DEMO,DEFAULT_TASTE,SCAN} from '../src/lib/coffee';
Object.defineProperty(globalThis,'crypto',{value:webcrypto,configurable:true});
const inv=addItems([],DEMO),fixed=()=>.1;
test('no coffee means no recipe',()=>assert.equal(makeRecipe(inv.filter(i=>!['coffee','espresso'].includes(i.category)),DEFAULT_TASTE,'hot'),null));
test('thresholds, quantities, order and surprise',()=>{const recipe=makeRecipe(inv,{boldness:100,sweetness:100,creaminess:100,flavor:100,foam:100},'surprise',fixed)!;assert.equal(recipe.temp,'hot');assert.equal(recipe.ingredients[0].amount,'3 shots (3 oz)');assert.equal(recipe.ingredients.filter(i=>i.label.includes('syrup')).length,2);assert.equal(recipe.ingredients.find(i=>i.label==='Oat milk')?.amount,'8 oz');assert.match(recipe.steps[0],/^Add/);assert(recipe.steps.some(s=>s.includes('big and fluffy')));assert.equal(recipe.name,'Dessert With Responsibilities');const iced=makeRecipe(inv,DEFAULT_TASTE,'surprise',()=>.8)!;assert.equal(iced.temp,'iced');assert(iced.steps.findIndex(s=>s.startsWith('Fill'))<iced.steps.findIndex(s=>s.startsWith('Froth')));});
test('cutoffs exclude extras, coffee uses scoops, no unavailable products',()=>{const r=makeRecipe(inv,{boldness:0,sweetness:5,creaminess:5,flavor:30,foam:0},'hot',fixed)!;assert.deepEqual(r.ingredients,[{label:'Medium roast',amount:'2 scoops + 8 oz water'}]);assert.equal(r.name,"Tomorrow's Problem");});
test('scan adds only new items, names dedupe ignoring spaces and case',()=>{const next=addItems(inv,SCAN);assert.equal(addItems(next,SCAN).length,next.length);assert.equal(addItems(next,[['  VANILLA SYRUP  ','syrup']]).length,next.length);});
test('recipes respect available foam equipment',()=>{const taste={boldness:50,sweetness:40,creaminess:50,flavor:40,foam:80};const noGear={steamer:false,frother:false};const hot=makeRecipe(inv,taste,'hot',fixed,noGear)!;assert.ok(hot.steps.some(s=>s.startsWith('Warm ')));assert.ok(!hot.steps.some(s=>/steam|froth/i.test(s)));const frother=makeRecipe(inv,taste,'hot',fixed,{steamer:false,frother:true})!;assert.ok(frother.steps.some(s=>s.startsWith('Warm, then froth')));const iced=makeRecipe(inv,taste,'iced',fixed,{steamer:true,frother:false})!;assert.ok(!iced.steps.some(s=>/steam|froth/i.test(s)));});

test('pot servings use two scoops per person and allow water changes',()=>{const t={boldness:100,sweetness:0,creaminess:0,flavor:0,foam:0};for(const [people,oz,n] of [[3,33,6],[3,30,6],[3,36,6],[6,66,12],[9,72,12]]){const r=makeRecipe(inv,t,'hot',fixed,{steamer:false,frother:false},{people,pot:true,waterOz:oz})!;assert.equal(r.ingredients[0].amount,`${n} scoops + ${oz} oz water`);}});
